### ISSUE TITLE
Not seeing pushbullet option available in pidgin

### ISSUE THREAD

**Issue by illepugil420** [EionRobb/pidgin-pushbullet#1]
I've downloaded the pushbullet dll and put it in c:\Program Files(x86)\Pidgin _and_ the C:\Program Files(x86)\Pidgin\plugins folder. I am not seeing pushbullet as an option in the account type.

**Comment by LordJair** [comment]
Seconded.

**Comment by EionRobb** [comment]
Just noticed that I accidentally compiled the dll badly.  I'll build a new one shortly

**Comment by EionRobb** [comment]
Ok, try grab a new copy from http://eion.robbmob.com/libpushbullet.dll - it should be more compatible with non-dev systems :)

**Comment by illepugil420** [comment]
Great. Copied it into the \plugins directiory and it comes up as an option now. Testing functionality as we speak.

**Comment by illepugil420** [comment]
Maybe I'm missing something, but how is this supposed to work? I didn't get an error after setting up the account, but my phone book isn't sync'd, and any message I send via that account to a cel # goes into the aether.

**Comment by LordJair** [comment]
In the Pidgin window for me when I try to send a message says, "Unable to send message."

edit: It does, however, come up with my contacts.

**Comment by illepugil420** [comment]
Update. I left my system sitting for while, came back, and I've got all my contacts, but i'm also getting the "unable to send message" error. I used my user id and app password for pushbullet.

This all being said, OMG thank you for working so hard on this.

**Comment by illepugil420** [comment]
Maybe it just had to sit for a while? It's working now with no further changes.

**Comment by illepugil420** [comment]
Ok, it's receiving messages at the moment, and I can send replies to myself back and forth. However, I'm getting errors sending as above to everyone but myself.

**Comment by EionRobb** [comment]
At the moment, it'll only send SMS to contacts whose phone number starts with a + or a number, so if there's (brackets) around the number it's not going to work just yet.

**Comment by EionRobb** [comment]
Ok, if the phone number has a bracket at the start then it'll count as an sms message now, if you want to give it a whirl.  http://eion.robbmob.com/libpushbullet.dll

If you're finding it not sending to other phone numbers, let me know and I'll dig into it some more

**Comment by illepugil420** [comment]
Alright! It looks like it's working, i'm texting several people on my list. However, when I send text messages I'm seeing a duplicate of the message appear in my IM window about 30 sec later. So 

Me: Hello
Me (30 sec later): Hello

Whereas only one 'Hello' is sent (and received). It does not give me a duplicate message when people reply. 

Also, numbers that start with () are not working still.

**Comment by EionRobb** [comment]
The duplicate sent one is your phone saying it sent it - there's a bit of delay as Pushbullet sends it down to the phone.   Still a bit rough around the edges, but I'll keep working on it more :)

**Comment by aesics** [comment]
I don't know if this is an issue with the plugin or Pushbullet but messages that I send via IM are not copied into the PushBullet program or webapp or the Android SMS program. The ones that I receive do show up in both these and the Android SMS program. This was not an issue with MightyText (if this helps at all). 

Thanks for the work you've put into this.

**Comment by EionRobb** [comment]
@aesics can you open a new issue with a debug log from Pidgin?

**Comment by EionRobb** [comment]
This issue has quickly mutated into something other than the original problem.... if you're having issues with the plugin, please open a new issue :)
