### ISSUE TITLE
Makefile fix

### ISSUE THREAD

**Issue by fognl** [EionRobb/pidgin-pushbullet#2]
This is either a Makefile fix, or a directory structure change.  Makefile expects icons to be in ./icons and not in top directory, which causes a make install fail.  Easy fix.

And for anyone else wondering, on Ubuntu 15.04, compiling this required pidgin-dev and libjson-glib-dev .

Thanks!

**Comment by apippin** [comment]
Commit 709ee8f29f9ffc3713e45dfb0cdc83ac31cc3e54 addressed/fixed this issue.
