### ISSUE TITLE
With new .dll, not receiving messages but can send

### ISSUE THREAD

**Issue by LordJair** [EionRobb/pidgin-pushbullet#3]
Is anyone having trouble with the newest .dll available through the link?  If I use a previous .dll (size = 63,796B), everything works but I'm getting the duplicates of my sent messages a few seconds later.  When I use the latest .dll (size = 72,311B), a sent message goes through, but no messages are received.

I've checked that both sent and received messages are working in Pushbullet itself.  Anyone having similar issues?

**Comment by EionRobb** [comment]
@LordJair are you still having the problem with the latest version?  If so, can you reopen the issue to discuss.  (Sorry I didn't respond to your message sooner)
