### ISSUE TITLE
Duplicate messages when sent

### ISSUE THREAD

**Issue by AKASecret** [EionRobb/pidgin-pushbullet#32]
When I send a message to someone with PushBullet, it duplicates my message on Pidgin but not actually on PushBullet.
![pidgin](https://user-images.githubusercontent.com/35233062/35923073-43489dc6-0bed-11e8-8062-90a7c9605f76.png)
![pb](https://user-images.githubusercontent.com/35233062/35923078-461e7476-0bed-11e8-855a-e635d490bbe9.png)

**Comment by apippin** [comment]
I have a fix pending for this issue. I've added a new option to the Advanced tab called "Don't echo back outbound SMS" and "Don't show SMS from this number:" which enables the plugin to filter these echo'd messages.

**Comment by apippin** [comment]
Should be fixed by #34
