### ISSUE TITLE
Pushbullet wont show in the account overview

### ISSUE THREAD

**Issue by veglar** [EionRobb/pidgin-pushbullet#9]
I've put the libpushbullet.dll into my windows `%APPDATA%\Roaming\.purple\plugins` folder. I expect to see Pushbullet as an Protocol option when try to add a new account.

I'm guessing one out of these two statements are true.

_I have not installed it correctly_
OR 
_There is something wrong with the plugin._

Could you please help me getting it right?

My Pidgin (Pidgin 2.10.11 (libpurple 2.10.11)) is installed on a Windows: 8.1 Pro Build 9600

**Comment by EionRobb** [comment]
Ah, of you haven't installed one of my plugins before, you're going to need the libjson-glib-1.0.dll in your C:/Program Files/Pidgin folder. I'll update the readme.

**Comment by veglar** [comment]
Thanks! 
I found it in one of your other projects and it did the trick. 

> Download the [json-glib library](https://github.com/EionRobb/pidgin-opensteamworks/raw/master/steam-mobile/libjson-glib-1.0.dll) into your Program Files (x86)\Pidgin folder (or Program Files\Pidgin), NOT into the plugins folder

**Comment by EionRobb** [comment]
I'll reopen the issue until I add the link to the readme :)
